"""Updated sim_card_id to String

Revision ID: 982f09f40ef5
Revises: 
Create Date: 2025-02-04 22:31:08.588952

"""
# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision = '982f09f40ef5'
# down_revision = None
# branch_labels = None
# depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('devices', schema=None) as batch_op:
#         batch_op.alter_column('sim_card_id',
#                existing_type=sa.INTEGER(),
#                type_=sa.String(length=20),
#                existing_nullable=True)

#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('devices', schema=None) as batch_op:
#         batch_op.alter_column('sim_card_id',
#                existing_type=sa.String(length=20),
#                type_=sa.INTEGER(),
#                existing_nullable=True)

#     # ### end Alembic commands ###
from alembic import op
import sqlalchemy as sa

# Drop the existing foreign key constraint
op.drop_constraint('devices_sim_card_id_fkey', 'devices', type_='foreignkey')

# Change the column type in the sim_cards table
op.alter_column('sim_cards', 'id',
    existing_type=sa.Integer(),
    type_=sa.String(20),
    existing_nullable=False)

# Change the column type in the devices table
op.alter_column('devices', 'sim_card_id',
    existing_type=sa.Integer(),
    type_=sa.String(20),
    existing_nullable=True)

# Recreate the foreign key constraint
op.create_foreign_key(
    'devices_sim_card_id_fkey', 'devices', 'sim_cards',
    ['sim_card_id'], ['id'],
    ondelete="SET NULL"
)
