"""Initial migration with VARCHAR IDs

Revision ID: a03fbe8348f8
Revises: 
Create Date: 2025-02-06 18:14:19.038058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a03fbe8348f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sim_cards',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('iccid', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iccid')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('sim_card_id', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.ForeignKeyConstraint(['sim_card_id'], ['sim_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_group_association', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'devices', ['device_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_group_association', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('devices')
    op.drop_table('sim_cards')
    # ### end Alembic commands ###
